#ifndef PICOPRO_SLICER_PATTERNS_H
#define PICOPRO_SLICER_PATTERNS_H

#include <stdint.h>

struct SliceStep {
  float gate;
  int8_t pitch;  // 0 / +/-12 semitones; SINGLE and TREMOLO ignore it.
  float pan;    // Reserved bipolar position; zero is center.
};

namespace slicer {

// Original patterns, not copied or decoded from BOSS SL-2 presets. Keeping
// this header private to the engine leaves the const bank in program flash.
#define SLICER_STEP(g) {g, 0, 0.0f}
#define SLICER_UP(g) {g, 12, 0.0f}
#define SLICER_DOWN(g) {g, -12, 0.0f}
static const SliceStep kPatterns[16][16] = {
  {SLICER_UP(1), SLICER_UP(1), SLICER_UP(1), SLICER_UP(1),
   SLICER_UP(1), SLICER_UP(1), SLICER_UP(1), SLICER_UP(1),
   SLICER_UP(1), SLICER_UP(1), SLICER_UP(1), SLICER_UP(1),
   SLICER_UP(1), SLICER_UP(1), SLICER_UP(1), SLICER_UP(1)},
  {SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0)},
  {SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0)},
  {SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0)},
  {SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0)},
  {SLICER_UP(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(1),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0)},
  {SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(1),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0)},
  {SLICER_STEP(1), SLICER_STEP(0), SLICER_UP(0.5f), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_DOWN(0.75f), SLICER_STEP(0), SLICER_UP(1),
   SLICER_STEP(0), SLICER_DOWN(0.5f), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(0.75f), SLICER_STEP(0)},
  {SLICER_UP(0.25f), SLICER_UP(0.5f), SLICER_UP(0.75f), SLICER_UP(1),
   SLICER_STEP(0.25f), SLICER_STEP(0.5f), SLICER_STEP(0.75f), SLICER_STEP(1),
   SLICER_DOWN(0.25f), SLICER_DOWN(0.5f), SLICER_DOWN(0.75f), SLICER_DOWN(1),
   SLICER_STEP(0.25f), SLICER_STEP(0.5f), SLICER_STEP(0.75f), SLICER_STEP(1)},
  {SLICER_DOWN(1), SLICER_DOWN(0.75f), SLICER_DOWN(0.5f), SLICER_DOWN(0.25f),
   SLICER_UP(1), SLICER_UP(0.75f), SLICER_UP(0.5f), SLICER_UP(0.25f),
   SLICER_STEP(1), SLICER_STEP(0.75f), SLICER_STEP(0.5f), SLICER_STEP(0.25f),
   SLICER_UP(1), SLICER_UP(0.75f), SLICER_UP(0.5f), SLICER_UP(0.25f)},
  {SLICER_UP(1), SLICER_STEP(0.4f), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(0.8f), SLICER_STEP(0.4f), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_UP(1), SLICER_DOWN(0.4f), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_STEP(0.8f), SLICER_STEP(0), SLICER_UP(0.4f), SLICER_STEP(0)},
  {SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(0.6f), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_DOWN(1), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_STEP(0), SLICER_UP(0.6f), SLICER_STEP(0)},
  {SLICER_UP(1), SLICER_UP(1), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_DOWN(1), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_STEP(1), SLICER_STEP(1), SLICER_UP(1), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(1), SLICER_DOWN(1), SLICER_STEP(0)},
  {SLICER_STEP(1), SLICER_STEP(0), SLICER_UP(1), SLICER_DOWN(0.5f),
   SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0), SLICER_STEP(0),
   SLICER_DOWN(0.75f), SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0),
   SLICER_DOWN(1), SLICER_STEP(0.5f), SLICER_STEP(0), SLICER_UP(1)},
  {SLICER_DOWN(0.0625f), SLICER_DOWN(0.125f), SLICER_DOWN(0.1875f), SLICER_DOWN(0.25f),
   SLICER_STEP(0.3125f), SLICER_STEP(0.375f), SLICER_STEP(0.4375f), SLICER_STEP(0.5f),
   SLICER_UP(0.5625f), SLICER_UP(0.625f), SLICER_UP(0.6875f), SLICER_UP(0.75f),
   SLICER_STEP(0.8125f), SLICER_STEP(0.875f), SLICER_STEP(0.9375f), SLICER_STEP(1)},
  {SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(0.5f), SLICER_STEP(0),
   SLICER_UP(1), SLICER_STEP(0), SLICER_DOWN(0.5f), SLICER_STEP(0),
   SLICER_STEP(0), SLICER_UP(0.75f), SLICER_STEP(0), SLICER_DOWN(0.75f),
   SLICER_STEP(0), SLICER_UP(1), SLICER_STEP(0.5f), SLICER_DOWN(1)},
};
#undef SLICER_STEP
#undef SLICER_UP
#undef SLICER_DOWN

}  // namespace slicer

#endif
