#!/usr/bin/env python3
"""Convert the stereo 24-bit PCM WAVs used by Grain into 16-bit flash tables."""

from pathlib import Path
import struct
import wave


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "Apps" / "Grain" / "Samples"
OUTPUT = ROOT / "Apps" / "Grain" / "grain_samples.h"
SOURCES = ("Downer.wav", "Guitar.wav")


def identifier(name: str) -> str:
    return "PICOPRO_GRAIN_" + "".join(c.upper() if c.isalnum() else "_" for c in name)


def read_pcm24_stereo(path: Path):
    with wave.open(str(path), "rb") as wav:
        if wav.getnchannels() != 2 or wav.getsampwidth() != 3:
            raise ValueError(f"{path}: expected stereo 24-bit PCM")
        if wav.getframerate() != 44100:
            raise ValueError(f"{path}: expected 44100 Hz")
        frames = wav.getnframes()
        raw = wav.readframes(frames)
    samples = []
    for offset in range(0, len(raw), 3):
        value = int.from_bytes(raw[offset:offset + 3], "little", signed=True)
        samples.append(max(-32768, min(32767, value >> 8)))
    return frames, samples


def main():
    converted = []
    for filename in SOURCES:
        path = SOURCE_DIR / filename
        frames, samples = read_pcm24_stereo(path)
        converted.append((path.stem, frames, samples))

    with OUTPUT.open("w", encoding="utf-8") as out:
        out.write("// Generated by Tools/import_grain_samples.py. Do not edit.\n")
        out.write("#ifndef PICOPRO_GRAIN_SAMPLES_H_\n#define PICOPRO_GRAIN_SAMPLES_H_\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("struct PicoGrainSample {\n")
        out.write("  const char *name;\n  const int16_t *data;\n  uint32_t frames;\n};\n\n")
        for name, frames, samples in converted:
            symbol = identifier(name)
            out.write(f"static const int16_t {symbol}[] = {{\n")
            for start in range(0, len(samples), 16):
                row = ", ".join(str(value) for value in samples[start:start + 16])
                out.write(f"  {row},\n")
            out.write("};\n\n")
        out.write("static const PicoGrainSample PICOPRO_GRAIN_SAMPLES[] = {\n")
        for name, frames, _ in converted:
            out.write(f'  {{"{name.lower()}", {identifier(name)}, {frames}u}},\n')
        out.write("};\n")
        out.write("#define PICOPRO_GRAIN_SAMPLE_COUNT ")
        out.write("(sizeof(PICOPRO_GRAIN_SAMPLES) / sizeof(PICOPRO_GRAIN_SAMPLES[0]))\n\n")
        out.write("#endif\n")


if __name__ == "__main__":
    main()
